# Generated by Django 3.2.3 on 2021-09-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_firstname', models.CharField(max_length=100)),
                ('employee_lastname', models.CharField(max_length=100)),
                ('employee_location', models.CharField(max_length=150)),
                ('employee_salary', models.IntegerField()),
                ('employee_department', models.CharField(max_length=50)),
            ],
        ),
    ]
